# Generated by Django 3.2.25 on 2024-11-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='num_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
