# Generated by Django 3.2.25 on 2024-11-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plate', '0002_alter_vehicle_num_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vid',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
