# Generated by Django 3.2.25 on 2024-11-24 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plate', '0003_auto_20241124_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 24, 18, 34, 8, 308688)),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='time',
            field=models.TimeField(default='18:34:08'),
        ),
    ]
