# Generated by Django 3.2.25 on 2024-11-24 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Plate', '0004_auto_20241124_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
